name: C/C++ CI

on:
    push:
        branches: [ dev, main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: make
          run: make
        - name: exe_player_one
          run: ./navy 32char
        - name: exe_player_two
          run: ./navy 666 32char
